name: Markdown Formatting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prettier
      run: npm install prettier

    - name: Test markdown formatting
      run: ./pretty-markdown.sh test
      
